name: CI/CD Pipeline

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Test & Lint
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json
          
      - name: Install dependencies
        run: |
          cd frontend
          npm ci --legacy-peer-deps
          
      - name: Run linting
        run: |
          cd frontend
          npm run lint
          
      - name: Run tests
        run: |
          cd frontend
          npm run test
          
      - name: Build application
        run: |
          cd frontend
          npm run build
          
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-files
          path: frontend/dist/

  deploy:
    name: Deploy to Firebase
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: Install dependencies
        run: |
          cd frontend
          npm ci --legacy-peer-deps
          cd ../functions
          npm ci
          cd ../functions-hse-ai
          npm ci
          cd ../hendrik
          npm ci
          
      - name: Build application
        run: |
          cd frontend
          npm run build
          
      - name: Install Firebase CLI
        run: npm install -g firebase-tools
          
      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          projectId: hse-ai-saas
          channelId: live
          
      - name: Deploy Functions
        run: |
          firebase deploy --only functions
          
      - name: Deploy Firestore Rules
        run: |
          firebase deploy --only firestore:rules

  security-scan:
    name: Security Scan
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Run security audit
        run: |
          cd frontend
          npm audit --audit-level=moderate
          
      - name: Run dependency check
        uses: dependency-check/Dependency-Check_Action@main
        with:
          project: 'HSE-AI-SaaS'
          path: '.'
          format: 'HTML'
          out: 'reports' 